prometheus:
  prometheusSpec:
    enableRemoteWriteReceiver: true

grafana:
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8
    hosts: 
      - grafana.emotoagh.eu.org
    tls:
     - secretName: emoto-agh-wildcard-certificate
       hosts:
       - grafana.emotoagh.eu.org

  additionalDataSources:
  - name: Tempo
    editable: true
    type: tempo
    url: http://tempo.observability.svc:3100
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: 'loki'
        tags: ['job', 'instance', 'pod', 'namespace']
        mappedTags: [{ key: 'service.name', value: 'service' }]
        mapTagNamesEnabled: false
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'
        filterByTraceID: false
        filterBySpanID: false
      tracesToMetrics:
        datasourceUid: 'prom'
        tags: [{ key: 'service.name', value: 'service' }, { key: 'job' }]
        queries:
          - name: 'Sample query'
            query: 'sum(rate(traces_spanmetrics_latency_bucket{$__tags}[5m]))'
      serviceMap:
        datasourceUid: 'prometheus'
      search:
        hide: false
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: 'loki'
    apiVersion: 1

  - name: Loki
    type: loki
    url: http://loki.observability:3100
    basicAuth: true
    jsonData:
      maxLines: 1000
      derivedFields:
        # Field with external link.
        - matcherRegex: "traceID=(\\w+)"
          name: TraceID
          url: 'http://localhost:16686/trace/$${__value.raw}'
    secureJsonData:
      basicAuthPassword: test_password

# values from: https://github.com/prometheus-community/helm-charts/blob/kube-prometheus-stack-45.8.1/charts/kube-prometheus-stack/values.yaml#L750