prometheus:
  prometheusSpec:
    enableRemoteWriteReceiver: true

grafana:
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8
    hosts: 
      - grafana.emotoagh.eu.org
    tls:
     - secretName: emoto-agh-wildcard-certificate
       hosts:
       - grafana.emotoagh.eu.org

  additionalDataSources:
  - name: Tempo
    editable: true
    type: tempo
    url: http://tempo.observability.svc:3100
    jsonData:
      httpMethod: GET
      tracesToMetrics:
        datasourceUid: 'prom'
        tags: [{ key: 'service.name', value: 'service' }, { key: 'job' }]
        queries:
          - name: 'Sample query'
            query: 'sum(rate(traces_spanmetrics_latency_bucket{$__tags}[5m]))'
      serviceMap:
        datasourceUid: 'prometheus'
      search:
        hide: false
      nodeGraph:
        enabled: true

# values from: https://github.com/prometheus-community/helm-charts/blob/kube-prometheus-stack-45.8.1/charts/kube-prometheus-stack/values.yaml#L750