apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: my-collector
  namespace: open-telemetry
spec:
  mode: daemonset
  config: |
    receivers:
      jaeger:
        protocols:
          grpc:
      otlp:
        protocols:
          grpc:
          http:
     # prometheus:
        # config:
        #   scrape_configs:
        #   - job_name: 'otel-collector'
        #     scrape_interval: 10s
        #     static_configs:
        #     - targets: ['0.0.0.0:8888']
          # - job_name: 'node'
          #   scrape_interval: 10s
          #   static_configs:
          #   - targets: ['localhost:9100']

    processors:

    exporters:
      logging:
        loglevel: debug
      otlp:
        endpoint: tempo.open-telemetry.svc:4317
        tls:
          insecure: true
      prometheus:
        endpoint: kube-prometheus-stack-prometheus.observability.svc:9464
      prometheusremotewrite:
        endpoint: http://kube-prometheus-stack-prometheus.observability.svc:9090/api/v1/write

    service:
      pipelines:
        traces:
          receivers: [otlp, jaeger]
          processors: []
          exporters: [logging, otlp]
        metrics:
          receivers: [otlp]
          processors: []
          exporters: [logging, prometheusremotewrite]